### PR TITLE
Migrate to null-safety

### PR DESCRIPTION
**Pull request by abordeau**
# Description

Migrate the lib to null-safety

## Type of change

- use `dart migrate` to check and update the code
- Add null-aware operator, where needed
- Bump sdk version to **2.12.0** to support null-safety
- Bump the version of the lib itself to reflect a major safe to **2.0.0**
- Add new tests to check some specific mode (**hasDigits**)

### CODE REVIEW

**Review by adrianflutur — APPROVED** [review]
Hi, 
Tested, no issues.
Thank you for the PR !

**Comment by abordeau** [comment]
You're welcome ! Thanks for this package 👌🏼
Do you think you can make this version available on [https://pub.dev/](https://pub.dev) ?

**Comment by adrianflutur** [comment]
Yes, it will be available very soon. I didn't do it just yet because there is a new feature available ([click](https://github.com/adrianflutur/random_string_generator/commit/8f53ec11f8fd3535a0d9a88812f74d29d08efad5)) and I want to test it a little bit more before doing so.

**Comment by abordeau** [comment]
Nice, that looks very promising !  👏 
Thanks again !

**Pull request merged**
